### ISSUE TITLE
encoding/gocode: Generate `any` instead of `interface{}`

### ISSUE THREAD

**Issue by sdboyer** [grafana/thema#138]
Now that `any` exists as a type in Go, we should generate it instead of `interface{}`.

I actually did this as part of #82, then rolled it back in e72fbab91f7a56ca02803ef70cd5e06cff931098 in order to help minimize the noise in the PR integrating #82 into grafana/grafana. Once that's done, doing this ticket should be as simple as reverting that commit.

**Comment by joanlopez** [comment]
Moved back to "Ready to start" because I guess it's no longer blocked (the flattening PR has been merged) and it could be a quick win for anyone open to pick it up!
