### ISSUE TITLE
Make Thema errors excellent: clear, actionable, informative

### ISSUE THREAD

**Issue by sdboyer** [grafana/thema#44]
For anyone not terribly interested in learning about the details of CUE and just wanting Thema to be a schema framework (our core target use case), validation error output is nearly indecipherable for anything outside of trivial cases. I laid out some examples in this grafana issue: grafana/grafana#37859

While there remain underlying things that CUE itself probably ought to fix - in particular, eliminating irrelevant disjunction branches in the presence of a discriminator field - we can actually probably do most or all of that directly in Thema. When it comes to generating comprehensible error messages, our job will always be easier, because we know enough about our inputs to be able to treat one input as schema, and the other as data compared against schema.

This can be done in stages. First will be just getting the basic scalar/enum-type validation failures improved. After that, we can layer on handling for more complex structures, like complex struct disjunctions.

Note that #8 has the potential to make those disjunction easier - if discimrinator fields are a property we can discern from the way that composition itself is declared, then we have all we need to do branch elimination.

- [x] #45 
- [x] Actually write some test suites, yikes
- [ ] Handle disjunctions

**Comment by frossano-grafana** [comment]
this is a usability issues, not a stability issue

**Comment by sdboyer** [comment]
#82 begins the use of github.com/cockroachdb/errors. However, there's a fair bit of planning and design on its own that needs to go into adopting the library - see [this whole design doc](https://github.com/cockroachdb/cockroach/blob/master/docs/RFCS/20190318_error_handling.md#Compatibility-and-differences-with-Go-2113-error-semantics) that covers the behaviors.

i could be talked out of it, but i think for the role we would like to see Thema occupy - a highly portable utility that can tuck into individual programs or complex operational topologies - ensuring our errors have the properties outlined in that document's [motivation section](https://github.com/cockroachdb/cockroach/blob/master/docs/RFCS/20190318_error_handling.md#motivation-for-a-new-error-library-summary) seems like the right move. i'm fine with a complex errors implementation inside thema, so long as it's simple to use on the outside.

**Comment by frossano-grafana** [comment]
I agree there is a fair bit of planning and design to do, and this is one of the things I talked abut with all the designers we interviewed. Error handling is both a technical and a usability issue, and we need to start from what we want to expose to final users and walk back to what we can achieve based on constraints in the implementation (there might be none, but there might be some big ones) 
Motivation behind the errors is super important, and for me in the end it boils down to: what do we want users to do when a specific error (or class of errors) comes out?

**Comment by sdboyer** [comment]
Closing in favor of #164
