### ISSUE TITLE
Add `thema lineage gen` subcommand to CLI

### ISSUE THREAD

**Issue by sdboyer** [grafana/thema#71]
Experience with using Thema within Grafana Labs has clearly shown that having a strong code generation story is the way to get to dopamine fastest with Thema.

Now that we have generics and in particular `ConvergentLineage`, it's feasible to fashion a simple, opinionated code generator as part of the CLI - `thema lineage gen` - that should be sufficient for anyone to:

* Write a lineage
* `thema lineage gen ...` to create Go bindings with a `ConvergentLineage`
* Get a vmuxer with a single line of handwritten code, and put it to work immediately

Having this will also mean we can eliminate 80% of the existing tutorials, as all of those needs will be automated away.

Initial targets for cli codegen: openapi, json schema, go, typescript

**Comment by joeblubaugh** [comment]
I love to see it
